### ISSUE TITLE
Make a .contract to generate a code for text files

### ISSUE THREAD

**Issue by hanaral** [sergius02/QRit#17]
Not sure what the limit for the amount of data a code can hold is, but AFAIK it's as detailed as the code can be
So it would be insane to be able to quickly scan a code and get all the text on my phone! I think that it would be useful for quickly copying small miscellanious text from elementary to your phone

**Comment by sergius02** [comment]
I was planning to add a text area instead a single line entry, to create QR from bigger text.

That's what you mean?

**Comment by hanaral** [comment]
>I was planning to add a text area instead a single line entry, to create QR from bigger text. ...

@sergius02 elementary uses the .contractor format for adding context menu items for elementary Files, you should look in to the documentation.
