### ISSUE TITLE
Minor Language Problem

### ISSUE THREAD

**Issue by kdwk** [sergius02/QRit#31]
**Describe the bug**
Spanish is used for some UI elements even when system language and the rest of the app is in English

**To Reproduce**
1. Click on 'open file' icon
2. What should've been 'cancel' and 'open' is now 'cancelar' and 'abrir'.

**Expected behavior**
1. The buttons should be labelled in English instead of Spanish.
**Screenshots**
![image](https://user-images.githubusercontent.com/39268094/102302288-b25b4380-3f93-11eb-9ee2-95d60e943874.png)

**Desktop (please complete the following information):**
 - OS: elementary OS 5.1.7 Hera

**Comment by sergius02** [comment]
Hi! this should be fixed since fe07f451ffe69aeefe10e6606bcce1e492f65e02 

You have download it from AppCenter? The update is currently been reviewed so could take some days to been approved.

**Comment by kdwk** [comment]
The update seems not to have gone through yet. Will close this issue after update arrives on AppCentre.

**Comment by kdwk** [comment]
Fixed
