### ISSUE TITLE
Change required for AppCenter: qrencode dependency not installed

### ISSUE THREAD

**Issue by cassidyjames** [sergius02/QRit#9]
When running [1.0.3 from the testing repo](http://packages.elementary.io/testing/pool/main/c/com.github.sergius02.qrit/com.github.sergius02.qrit1.0.3-46dfe8.deb) on a fresh install, I get this in the Terminal:

`Failed to execute child process “qrencode” (No such file or directory)`

It seems like you need to include `qrencode` as a dependency in your packaging. Please resolve this, create a new release on GitHub, and submit that release to the [AppCenter Dashboard](https://developer.elementary.io/). As always, if you have any questions, feel free to ask here.

**Comment by sergius02** [comment]
Strange, i already have qrencode as a dependency in control file https://github.com/sergius02/QRit/blob/566800e985465fc8fd102b68d4e67fb157cf8d9b/debian/control#L7
